### PR TITLE
Closes #302. Implements theme appropriate tooltip coloring

### LINKED ISSUE #302: [Feature Request] Dark tool-tips in Dark (Gray) Mode
Chromium 62, no BTTV, just FFZ. Tooltips in Dark/Gray Mode have white background, it would be nice to change them to have a dark background in this mode. I'm talking about the emote tooltips (large version of emotes), badge tooltips, uptime tooltip, stream latency tooltip, etc.

### PR DESCRIPTION
**Pull request by Dgc2002**

### CODE REVIEW

**Comment by Dgc2002** [comment]
Result:    
Emote  
  
Badges

**Comment by SirStendec** [comment]
This is something I've been planning to add, but there needs to be a setting to control if this is enabled. Eventually, there's going to be a complete overhaul of the dark theme into a more broad theme system.

Also, the other pull request should be part of this. They're all tool-tips, whether enhanced FFZ tips or default Twitch tips.

**Comment by Dgc2002** [comment]
Merged #307 into this.  
  
And you're right, I see now that these CSS overrides are all grouped together regardless of light/dark theme. Still familiarizing myself with the project layout.  
  
Feel free to close these PRs then since they don't take the light theme into account.

**Comment by SirStendec** [comment]
I'll close this and set up a bigger issue for theme stuff.

**Pull request closed without merging**
